### ISSUE TITLE
Plugin sometimes fails to read the returned JSON from ambientweather on reboot

### ISSUE THREAD

**Issue by cytan299** [peledies/Homebridge-Ambient-Weather-Temperature-Sensor#10] opened 2024-01-24 00:30 UTC
**Describe The Bug:**

Sometimes, a reboot will fail because the plugin doesn't read the JSON properly from ambientweather on reboot.

**To Reproduce:**

Rebooting.

**Expected behavior:**

There should not be an error

**Logs:**

```
[21/01/2024, 10:09:58] [AmbientWeatherSensors] ERROR: invalid json response body at https://rt.ambientweather.net/v1/devices?applicationKey=xxx&apiKey=xxx reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
TypeError: Cannot read properties of undefined (reading 'filter')
    at HumidityAccessory.updateData (/var/lib/homebridge/node_modules/homebridge-ambient-weather-sensors/src/humidityAccessory.ts:49:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Plugin Config:**

```json
{
    "name": "AmbientWeatherSensors",
    "apiKey": "xxx",
    "applicationKey": "xxx",
    "temperatureSensors": true,
    "humiditySensors": true,
    "solarRadiationSensors": false,
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 41348
    },
    "platform": "AmbientWeatherSensors"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1..7.0
* **Node.js Version**: 20.11.0
* **NPM Version**: 10.2.4
* **Operating System**:  RAspbian

**Comment by peledies** [comment] 2024-01-26 00:12
This appears to be a duplicate of the following issue: https://github.com/peledies/homebridge-ambient-weather-sensors/issues/9

**Closed as completed by peledies** 2024-01-26 00:12 UTC
Labels: bug, duplicate
